AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Provision AWS resources for The Button App

Parameters:
  DBUsername:
    NoEcho: "true"
    Type: String
    Default: "{{resolve:secretsmanager:TheButtonDBSecret:SecretString:username}}"
  DBPassword:
    NoEcho: "true"
    Type: String
    Default: "{{resolve:secretsmanager:TheButtonDBSecret:SecretString:password}}"
  DBAllocatedStorage:
    Type: Number
    Default: "20" # 20 GiB is the maximum allotted amount in AWS Free Tier

Mappings:
  "007633048842":
    us-east-1:
      Subnets:
        - subnet-0e095e2769d23ca5d
        - subnet-01df7bbd76be6caa1
        - subnet-03fc03e25c93956a9
        - subnet-02bab21ccb7ee2e0e
        - subnet-00a476a971ffb8a92
        - subnet-0c1f63a07540c9663
      SecurityGroups:
        - sg-0365b4fc7d010bdb4
      InstanceType: db.t3.micro
      BackupRetentionPeriod: 7

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Database Configuration
        Parameters:
          - DBUsername
          - DBPassword
    ParameterLabels:
      DatabaseUsername:
        default: !Ref DBUsername
      DatabasePassword:
        default: !Ref DBPassword

Resources:
  # RDS
  # DBSubnetGroup:
  #   Type: AWS::RDS::DBSubnetGroup
  #   Properties:
  #     SubnetIds:
  #       !FindInMap [!Ref "AWS::AccountId", !Ref "AWS::Region", "Subnets"]

  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      DBSecurityGroupIngress:
        - EC2SecurityGroupId: sg-0365b4fc7d010bdb4
          EC2SecurityGroupOwnerId: 007633048842

  DBPrimaryInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: MySQL
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass:
        !FindInMap [!Ref "AWS::AccountId", !Ref "AWS::Region", "InstanceType"]
      DBSecurityGroups:
        - Ref: DBSecurityGroup
      # DBSubnetGroupName: !Ref DBSubetGroup
      AllocatedStorage: !Ref DBAllocatedStorage
      PubliclyAccessible: True
