AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Provision AWS resources for The Button App

# Parameters:
#   DatabaseUsername:
#     Type: String
#     Default: "{{resolve:secretsmanager:TheButtonDBSecret:SecretString:username}}"
#   DatabasePassword:
#     NoEcho: "true"
#     Type: String
#     Default: "{{resolve:secretsmanager:TheButtonDBSecret:SecretString:password}}"

Mappings:
  "007633048842":
    us-east-1:
      Subnets:
        - subnet-0e095e2769d23ca5d
        - subnet-01df7bbd76be6caa1
        - subnet-03fc03e25c93956a9
        - subnet-02bab21ccb7ee2e0e
        - subnet-00a476a971ffb8a92
        - subnet-0c1f63a07540c9663
      SecurityGroups:
        - sg-0adf6a5110fa4c2a9
      InstanceType: db.t2.micro # this is just for testing, need to change eventually
      BackupRetentionPeriod: 7

# Metadata:
#   AWS::CloudFormation::Interface:
#     ParameterGroups:
#       - Label:
#           default: Database Configuration
#         Parameters:
#           - DatabaseUsername
#           - DatabasePassword
#     ParameterLabels:
#       DatabaseUsername:
#         default: !Ref DatabaseUsername
#       DatabasePassword:
#         default: !Ref DatabasePassword

Resources:
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: CloudFormation managed DB subnet group.
      SubnetIds:
        !FindInMap [!Ref "AWS::AccountId", !Ref "AWS::Region", "Subnets"]

  DatabasePrimaryInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: MySQL
      MasterUsername: "{{resolve:secretsmanager:TheButtonDBSecret:SecretString:username}}"
      MasterUserPassword: "{{resolve:secretsmanager:TheButtonDBSecret:SecretString:password}}"
      DBInstanceClass:
        !FindInMap [!Ref "AWS::AccountId", !Ref "AWS::Region", "InstanceType"]
      DBSubnetGroupName: !Ref "DatabaseSubnetGroup"
      PubliclyAccessible: True
      AllocatedStorage: "20"
